# Generated by Django 3.1.6 on 2021-02-20 18:35

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='住所')),
            ],
            options={
                'db_table': 'location',
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='タイトル')),
                ('text', models.TextField(blank=True, null=True, verbose_name='本文')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='画像')),
                ('posted_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='投稿日時')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='投稿者')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='map.location', verbose_name='座標')),
            ],
            options={
                'db_table': 'note',
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='本文')),
                ('posted_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='投稿日時')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='投稿者')),
                ('response_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.note', verbose_name='返信先')),
            ],
            options={
                'db_table': 'response',
            },
        ),
    ]
