# Generated by Django 3.1.6 on 2021-02-13 03:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('map', '0002_auto_20210207_2241'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='タイトル')),
                ('text', models.TextField(blank=True, null=True, verbose_name='本文')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='画像')),
                ('post_date', models.DateTimeField(blank=True, null=True, verbose_name='投稿日')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='map.location', verbose_name='座標')),
                ('post_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='投稿者')),
                ('response_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='map.note', verbose_name='返信先')),
            ],
            options={
                'db_table': 'note',
            },
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
