# Generated by Django 3.1.6 on 2021-02-13 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_auto_20210213_1210'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='location',
            new_name='point',
        ),
    ]
