# Generated by Django 3.1.6 on 2021-02-14 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('map', '0005_auto_20210214_0147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='post_user',
            new_name='author',
        ),
        migrations.RemoveField(
            model_name='location',
            name='zip_code',
        ),
        migrations.RemoveField(
            model_name='note',
            name='post_date',
        ),
        migrations.RemoveField(
            model_name='note',
            name='response_post',
        ),
        migrations.AddField(
            model_name='note',
            name='posted_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='投稿日時'),
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='本文')),
                ('posted_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='投稿日時')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='投稿者')),
                ('response_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.note', verbose_name='返信先')),
            ],
            options={
                'db_table': 'response',
            },
        ),
    ]
